# EXPERIMENT 2
## Name: Macuno, Aaron Josh F.
## Section: 2ECE-A
## Date Submitted: September 3, 2024

### --------------------------------------------------------------------------------------------------------------------------------

### Normalization Problem

In [100]:
import numpy as np

# 5x5 array with random numbers stored in the variable X
X = np.random.rand(5, 5)  

# Storing the given formula with the variable X_normalized
X_normalized = (X - X.mean()) / X.std()

# Saving the X_normalized array
np.save('X_normalized.npy', X_normalized)

print("\033[1m The Matrix is \033[0m \n\n",X,
      "\n\n" "\033[1m The Mean is\033[0m", X.mean(),
      "\n\n" "\033[1m The Standard Deviation is \033[0m", X.std(),
      "\n\n" "\033[1m The Normalized Matrix is \033[0m \n\n", X_normalized)

 The Matrix is  

 [[0.52277644 0.69925031 0.42445549 0.05839568 0.9996405 ]
 [0.45733332 0.65830019 0.96814176 0.7901024  0.64677318]
 [0.06834332 0.52624782 0.51453095 0.54829027 0.39056383]
 [0.02259423 0.53222212 0.3186226  0.84269266 0.52289782]
 [0.3259768  0.96777588 0.84393603 0.81182958 0.54167307]] 

 The Mean is 0.5601346500542007 

 The Standard Deviation is  0.26830059507591236 

 The Normalized Matrix is  

 [[-0.13924013  0.5185067  -0.5056983  -1.87006282  1.63810984]
 [-0.38315728  0.36587897  1.52070894  0.85712723  0.32291589]
 [-1.83298636 -0.12630172 -0.16997242 -0.04414593 -0.63201806]
 [-2.00350064 -0.10403454 -0.90015473  1.05313972 -0.13878771]
 [-0.87274444  1.51934522  1.05777395  0.93810797 -0.06880933]]


### Divisible by 3 Problem 

In [53]:
import numpy as np

# A matrix with 1 to 100 numbers that are given in squared form
A = np.arange(1,101)**2

# Using the .reshape to reshape the matrix in a 10x10 
A = A.reshape(10,10)

# A function that will only get those numbers that are divisible by 3
def divisibility_by_3(array):
    array = array[A%3==0]
    return array

# Saving the divisibility_by_3 function
np.save("div_by_3.npy",divisibility_by_3(A))

# Using the div_by_3.npy file and putting it in the said matrix
div3_A = np.load("div_by_3.npy")

print("\033[1m A 10x10 matrix with squared values ranging from 1 to 100 \033[0m \n\n", A,
     "\n\n" "\033[1m A 10x10 matrix ranging from 1 to 100 with numbers only divisible by 3 \033[0m \n\n", div3_A )

 A 10x10 matrix with squared values ranging from 1 to 100  

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

 A 10x10 matrix ranging from 1 to 100 with numbers only divisible by 3  

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
